config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:new, :create], path: '/register', path_names: { new: '/'}
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/'}
  end

    # Defines the root path route ("/")
  # root "posts#index"
  # root "products#index"
   #Cuando soliciten /products devuelvo el controlador products como me va a devolver un conjunto de cosas le agrego como nombre de metodo index
  # post '/products',     to: 'products#create'
  # get  '/products/new', to: 'products#new', as: :new_product
  # get  '/products',     to: 'products#index'
  # get  '/products/:id', to: 'products#show', as: :product
  # get  '/products/:id/edit', to: 'products#edit', as: :edit_product
  # patch '/products/:id', to: 'products#update'
  # delete '/products/:id', to: 'products#destroy'
  #Escribir resources products es equivalente a poner las 7 lineas de arriba

  resources :categories, except: :show
  resources :users, only: :show,  path: '/user' , param: :username
  resources :favorites, only: [:create, :destroy, :index], param: :product_id
    #ojo con el orden aca , la home / debe ir abajo
  resources :products, path: '/'
end

app/views/shared/_flash.html.erb
<%= notice %>
<%= alert %>

<%=  %>

app/views/shared/_footer.html.erb
<footer class="footer bg-white text-tertiary p-4 text-center">
  <p>EM;</p>
  <p>
    <a href="https://github.com/Matijasevic-Emer" target="_blank" class="hover:underline">GitHub</a> |
    <a href="https://www.linkedin.com/in/emerson-matijasevic/" target="_blank" class="hover:underline">LinkedIn</a> |
    <a href="https://www.youtube.com/watch?v=0Qj3LUxx3Zg&list=PLP06kydD_xaUS6plnsdonHa5ySbPx1PrP&index=2" target="_blank" class="hover:underline">Inspiración</a>
  </p>
</footer>

app/views/shared/_header.html.erb
<header class="bg-white text-claro p-4" id="header">
  <div class="flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">
    <!-- Brand / Logo -->
    <div class="brand text-lg font-bold">
      <%= link_to products_path do %>
        <h1 class="text-4xl font-bold text-primary inline-block">
          <%= t('app_name') %>
          <%= image_tag 'favicon.ico', alt: t('app_name'), class: 'inline-block ml-2' %>
        </h1>
      <% end %>
    </div>

    <!-- Settings Links -->
    <div class="settings flex flex-col md:flex-row md:space-x-4 items-center">
      <% if !Current.user %>
        <%= link_to new_session_path, class: "hover:underline text-primary mb-2 md:mb-0" do %>
          <h3><%= t('.login') %></h3>
        <% end %>
      <% else %>
        <%= link_to session_path(Current.user.id),
                    data: { turbo_confirm: t('common.confirm'), turbo_method: :delete },
                    class: "hover:underline text-primary mb-2 md:mb-0" do %>
          <h3 class="text-primary"><%= t('.logout') %></h3>
        <% end %>
        <%= link_to favorites_path, class: "hover:underline mb-2 md:mb-0" do %>
          <h3 class="text-primary"><%= t('.my_favorites') %></h3>
        <% end %>
      <% end %>

      <% if Current.user&.admin? %>
        <%= link_to categories_path, class: "hover:underline text-primary mb-2 md:mb-0" do %>
          <h3><%= t('.category') %></h3>
        <% end %>

      <% end %>
      <!-- Dropdown for language selection -->
      <div class="relative">
        <button class="dropbtn bg-primary text-white p-2 rounded-md mb-2 md:mb-0" onclick="toggleDropdown()">Idioma</button>
        <div class="absolute bg-white text-black mt-2 py-2 rounded-md shadow-md hidden" id="language-dropdown">
          <%= link_to 'Inglés: 🇬🇧', url_for(locale: 'en'), class: 'block px-4 py-2 hover:bg-tertiary hover:text-black' %>
          <%= link_to 'Español: 🇪🇸', url_for(locale: 'es'), class: 'block px-4 py-2 hover:bg-tertiary hover:text-black' %>
          <%= link_to 'Croata: 🇭🇷', url_for(locale: 'hr'), class: 'block px-4 py-2 hover:bg-tertiary hover:text-black' %>
        </div>
      </div>
    </div>
  </div>
</header>

<script>
    function toggleDropdown() {
        const dropdown = document.getElementById('language-dropdown');
        dropdown.classList.toggle('hidden');
    }

    // Close dropdown if clicked outside
    window.onclick = function(event) {
        if (!event.target.matches('.dropbtn')) {
            const dropdowns = document.getElementsByClassName("absolute");
            for (let i = 0; i < dropdowns.length; i++) {
                const openDropdown = dropdowns[i];
                if (!openDropdown.classList.contains('hidden')) {
                    openDropdown.classList.add('hidden');
                }
            }
        }
    }
</script>